import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import Post from '../components/Post/Post';
import { store } from '../app/store';
import { Provider } from 'react-redux';

const H1 = styled.h1`
  text-align: center;
  margin-bottom: 4rem;
`;

const Home: NextPage = () => {
  return (
    <Provider store={store}>
      <div>
        <Head>
          <title>Instagram post app</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <H1>Instagram post</H1>

        <Post />
      </div>
    </Provider>
  );
};

export default Home;
